custom:
  profile: umihico # aws account configured in ~/.aws/credentials
  service: myportfolio # project name

service:
  name: ${self:custom.service}

provider:
  name: aws
  region: ap-northeast-1
  runtime: provided
  stage: stg
  profile: ${self:custom.profile}
  environment:
    APP_STORAGE: '/tmp'
    ENV: ${opt:stage, self:provider.stage}

plugins:
  - ./vendor/bref/bref

functions:
  laravel:
    handler: public/index.php
    timeout: 28
    layers:
      - ${bref:layer.php-73-fpm}
    events:
      - http: 'ANY /'
      - http: 'ANY /{proxy+}'

package:
  exclude:
    - node_modules/**
    - .git/**